/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepositoriesIdIndexRouteImport } from './routes/repositories.$id.index'
import { Route as RepositoriesIdCyclesCycleIdRouteImport } from './routes/repositories.$id.cycles.$cycleId'

const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesIdIndexRoute = RepositoriesIdIndexRouteImport.update({
  id: '/repositories/$id/',
  path: '/repositories/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesIdCyclesCycleIdRoute =
  RepositoriesIdCyclesCycleIdRouteImport.update({
    id: '/repositories/$id/cycles/$cycleId',
    path: '/repositories/$id/cycles/$cycleId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/findings': typeof FindingsRoute
  '/repositories/$id/': typeof RepositoriesIdIndexRoute
  '/repositories/$id/cycles/$cycleId': typeof RepositoriesIdCyclesCycleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/findings': typeof FindingsRoute
  '/repositories/$id': typeof RepositoriesIdIndexRoute
  '/repositories/$id/cycles/$cycleId': typeof RepositoriesIdCyclesCycleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/findings': typeof FindingsRoute
  '/repositories/$id/': typeof RepositoriesIdIndexRoute
  '/repositories/$id/cycles/$cycleId': typeof RepositoriesIdCyclesCycleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/findings'
    | '/repositories/$id/'
    | '/repositories/$id/cycles/$cycleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/findings'
    | '/repositories/$id'
    | '/repositories/$id/cycles/$cycleId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/findings'
    | '/repositories/$id/'
    | '/repositories/$id/cycles/$cycleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FindingsRoute: typeof FindingsRoute
  RepositoriesIdIndexRoute: typeof RepositoriesIdIndexRoute
  RepositoriesIdCyclesCycleIdRoute: typeof RepositoriesIdCyclesCycleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$id/': {
      id: '/repositories/$id/'
      path: '/repositories/$id'
      fullPath: '/repositories/$id/'
      preLoaderRoute: typeof RepositoriesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$id/cycles/$cycleId': {
      id: '/repositories/$id/cycles/$cycleId'
      path: '/repositories/$id/cycles/$cycleId'
      fullPath: '/repositories/$id/cycles/$cycleId'
      preLoaderRoute: typeof RepositoriesIdCyclesCycleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FindingsRoute: FindingsRoute,
  RepositoriesIdIndexRoute: RepositoriesIdIndexRoute,
  RepositoriesIdCyclesCycleIdRoute: RepositoriesIdCyclesCycleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
